


source_files	:= $(wildcard *.c)


build-and-run: build clean-screen run


build: arvoreBEstrela.exe


clean-screen:
	clear


run:
	@./arvoreBEstrela.exe



arvoreBEstrela.exe:
	gcc arvoreBEstrela.c -o $@ -Wall


